# Generated by Django 3.2.20 on 2023-11-11 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplePaperSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.samplepaper')),
            ],
        ),
    ]
