# Generated by Django 3.2.20 on 2023-11-17 17:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSpecificAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'gif'])])),
                ('description', models.CharField(max_length=280)),
                ('time', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('Batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.batch')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.facultymodel')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'gif'])])),
                ('description', models.CharField(max_length=280)),
                ('time', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('faculty_only', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.facultymodel')),
            ],
        ),
    ]
