# Generated by Django 3.2.20 on 2023-11-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultymodel',
            name='is_department_head',
        ),
    ]
