# Generated by Django 3.2.20 on 2023-10-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('CSEAIML', 'Computer Science and Engineering (AI/ML)'), ('CSEDS', 'Computer Science and Engineering (Data Science)'), ('IT', 'Information Technology'), ('CS', 'Computer Science'), ('AIML', 'Artificial Intelligence and Machine Learning'), ('CSIT', 'Computer Science and Information Technology'), ('EN', 'Electrical And Electronics Engineering'), ('CSEH', 'Computer Science and Engineering (Hindi)')], max_length=8)),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')])),
                ('course_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.IntegerField(unique=True)),
                ('roll_number', models.IntegerField(unique=True)),
                ('current_semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')])),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('CSEAIML', 'Computer Science and Engineering (AI/ML)'), ('CSEDS', 'Computer Science and Engineering (Data Science)'), ('IT', 'Information Technology'), ('CS', 'Computer Science'), ('AIML', 'Artificial Intelligence and Machine Learning'), ('CSIT', 'Computer Science and Information Technology'), ('EN', 'Electrical And Electronics Engineering'), ('CSEH', 'Computer Science and Engineering (Hindi)')], max_length=8)),
                ('contact_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_contact_number', models.IntegerField()),
                ('courses', models.ManyToManyField(to='accounts.Course')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('contact_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('department', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('CSEAIML', 'Computer Science and Engineering (AI/ML)'), ('CSEDS', 'Computer Science and Engineering (Data Science)'), ('IT', 'Information Technology'), ('CS', 'Computer Science'), ('AIML', 'Artificial Intelligence and Machine Learning'), ('CSIT', 'Computer Science and Information Technology'), ('EN', 'Electrical And Electronics Engineering'), ('CSEH', 'Computer Science and Engineering (Hindi)')], max_length=8)),
                ('is_department_head', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(to='accounts.Course')),
            ],
        ),
    ]
