# Generated by Django 3.2.20 on 2023-11-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymodel',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='guardian_contact_number',
            field=models.BigIntegerField(),
        ),
    ]
