# Generated by Django 3.2.20 on 2023-11-10 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.semester'),
        ),
        migrations.AlterField(
            model_name='facultymodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='current_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.semester'),
        ),
    ]
