# Generated by Django 3.2.20 on 2023-10-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
