# Generated by Django 3.2.20 on 2023-11-07 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_facultymodel_is_department_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='faculty',
        ),
        migrations.CreateModel(
            name='BatchCourseFacultyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.facultymodel')),
            ],
        ),
    ]
