# Generated by Django 3.2.20 on 2023-11-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentmodel_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='address',
        ),
    ]
