# Generated by Django 4.2.6 on 2023-10-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_studentmodel_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='profile_pics/'),
        ),
    ]
