# Generated by Django 3.2.20 on 2023-11-19 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('room', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LectureNumberModel',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeTableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.batch')),
                ('lectures', models.ManyToManyField(to='timetable.LectureModel')),
            ],
        ),
        migrations.AddField(
            model_name='lecturemodel',
            name='lecture_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.lecturenumbermodel'),
        ),
        migrations.AddField(
            model_name='lecturemodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.batchcoursefacultyassignment'),
        ),
        migrations.AlterUniqueTogether(
            name='lecturemodel',
            unique_together={('lecture_number', 'day')},
        ),
    ]
