# Generated by Django 3.2.20 on 2023-11-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturenumbermodel',
            old_name='number',
            new_name='slot',
        ),
    ]
