# Generated by Django 3.2.20 on 2023-11-20 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_profile_picture'),
        ('timetable', '0002_rename_number_lecturenumbermodel_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturemodel',
            old_name='lecture_number',
            new_name='slot_number',
        ),
        migrations.AlterUniqueTogether(
            name='lecturemodel',
            unique_together={('slot_number', 'day', 'subject')},
        ),
    ]
