# Generated by Django 3.2.20 on 2023-11-11 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesheet',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.batchcoursefacultyassignment'),
        ),
        migrations.AlterField(
            model_name='attendancesheet',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesheet',
            unique_together={('assignment', 'date')},
        ),
        migrations.RemoveField(
            model_name='attendancesheet',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='attendancesheet',
            name='course',
        ),
    ]
