# Generated by Django 3.2.20 on 2023-11-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('attendence', '0002_auto_20231111_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancesheet',
            old_name='assignment',
            new_name='batch',
        ),
        migrations.AlterUniqueTogether(
            name='attendancesheet',
            unique_together={('batch', 'date')},
        ),
    ]
